// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImgClassify.proto

package com.proto.ImgClassify;

public final class ImgClassify {
  private ImgClassify() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface imgsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gesture_rpc.imgs)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string ID = 1;</code>
     */
    java.lang.String getID();
    /**
     * <code>string ID = 1;</code>
     */
    com.google.protobuf.ByteString
        getIDBytes();

    /**
     * <code>int32 num_img = 2;</code>
     */
    int getNumImg();

    /**
     * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
     */
    java.util.List<com.proto.ImgClassify.ImgClassify.imgs.img> 
        getAllImgList();
    /**
     * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
     */
    com.proto.ImgClassify.ImgClassify.imgs.img getAllImg(int index);
    /**
     * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
     */
    int getAllImgCount();
    /**
     * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
     */
    java.util.List<? extends com.proto.ImgClassify.ImgClassify.imgs.imgOrBuilder> 
        getAllImgOrBuilderList();
    /**
     * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
     */
    com.proto.ImgClassify.ImgClassify.imgs.imgOrBuilder getAllImgOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code gesture_rpc.imgs}
   */
  public  static final class imgs extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gesture_rpc.imgs)
      imgsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use imgs.newBuilder() to construct.
    private imgs(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private imgs() {
      iD_ = "";
      allImg_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private imgs(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              iD_ = s;
              break;
            }
            case 16: {

              numImg_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                allImg_ = new java.util.ArrayList<com.proto.ImgClassify.ImgClassify.imgs.img>();
                mutable_bitField0_ |= 0x00000004;
              }
              allImg_.add(
                  input.readMessage(com.proto.ImgClassify.ImgClassify.imgs.img.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          allImg_ = java.util.Collections.unmodifiableList(allImg_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.ImgClassify.ImgClassify.internal_static_gesture_rpc_imgs_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.ImgClassify.ImgClassify.internal_static_gesture_rpc_imgs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.ImgClassify.ImgClassify.imgs.class, com.proto.ImgClassify.ImgClassify.imgs.Builder.class);
    }

    public interface imgOrBuilder extends
        // @@protoc_insertion_point(interface_extends:gesture_rpc.imgs.img)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>repeated int32 single_img = 1;</code>
       */
      java.util.List<java.lang.Integer> getSingleImgList();
      /**
       * <code>repeated int32 single_img = 1;</code>
       */
      int getSingleImgCount();
      /**
       * <code>repeated int32 single_img = 1;</code>
       */
      int getSingleImg(int index);
    }
    /**
     * Protobuf type {@code gesture_rpc.imgs.img}
     */
    public  static final class img extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:gesture_rpc.imgs.img)
        imgOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use img.newBuilder() to construct.
      private img(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private img() {
        singleImg_ = emptyIntList();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private img(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                  singleImg_ = newIntList();
                  mutable_bitField0_ |= 0x00000001;
                }
                singleImg_.addInt(input.readInt32());
                break;
              }
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                  singleImg_ = newIntList();
                  mutable_bitField0_ |= 0x00000001;
                }
                while (input.getBytesUntilLimit() > 0) {
                  singleImg_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) != 0)) {
            singleImg_.makeImmutable(); // C
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.proto.ImgClassify.ImgClassify.internal_static_gesture_rpc_imgs_img_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.proto.ImgClassify.ImgClassify.internal_static_gesture_rpc_imgs_img_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.proto.ImgClassify.ImgClassify.imgs.img.class, com.proto.ImgClassify.ImgClassify.imgs.img.Builder.class);
      }

      public static final int SINGLE_IMG_FIELD_NUMBER = 1;
      private com.google.protobuf.Internal.IntList singleImg_;
      /**
       * <code>repeated int32 single_img = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getSingleImgList() {
        return singleImg_;
      }
      /**
       * <code>repeated int32 single_img = 1;</code>
       */
      public int getSingleImgCount() {
        return singleImg_.size();
      }
      /**
       * <code>repeated int32 single_img = 1;</code>
       */
      public int getSingleImg(int index) {
        return singleImg_.getInt(index);
      }
      private int singleImgMemoizedSerializedSize = -1;

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (getSingleImgList().size() > 0) {
          output.writeUInt32NoTag(10);
          output.writeUInt32NoTag(singleImgMemoizedSerializedSize);
        }
        for (int i = 0; i < singleImg_.size(); i++) {
          output.writeInt32NoTag(singleImg_.getInt(i));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        {
          int dataSize = 0;
          for (int i = 0; i < singleImg_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(singleImg_.getInt(i));
          }
          size += dataSize;
          if (!getSingleImgList().isEmpty()) {
            size += 1;
            size += com.google.protobuf.CodedOutputStream
                .computeInt32SizeNoTag(dataSize);
          }
          singleImgMemoizedSerializedSize = dataSize;
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.proto.ImgClassify.ImgClassify.imgs.img)) {
          return super.equals(obj);
        }
        com.proto.ImgClassify.ImgClassify.imgs.img other = (com.proto.ImgClassify.ImgClassify.imgs.img) obj;

        if (!getSingleImgList()
            .equals(other.getSingleImgList())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getSingleImgCount() > 0) {
          hash = (37 * hash) + SINGLE_IMG_FIELD_NUMBER;
          hash = (53 * hash) + getSingleImgList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.proto.ImgClassify.ImgClassify.imgs.img parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.proto.ImgClassify.ImgClassify.imgs.img parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.proto.ImgClassify.ImgClassify.imgs.img parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.proto.ImgClassify.ImgClassify.imgs.img parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.proto.ImgClassify.ImgClassify.imgs.img parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.proto.ImgClassify.ImgClassify.imgs.img parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.proto.ImgClassify.ImgClassify.imgs.img parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.proto.ImgClassify.ImgClassify.imgs.img parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.proto.ImgClassify.ImgClassify.imgs.img parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.proto.ImgClassify.ImgClassify.imgs.img parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.proto.ImgClassify.ImgClassify.imgs.img parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.proto.ImgClassify.ImgClassify.imgs.img parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.proto.ImgClassify.ImgClassify.imgs.img prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code gesture_rpc.imgs.img}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:gesture_rpc.imgs.img)
          com.proto.ImgClassify.ImgClassify.imgs.imgOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.proto.ImgClassify.ImgClassify.internal_static_gesture_rpc_imgs_img_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.proto.ImgClassify.ImgClassify.internal_static_gesture_rpc_imgs_img_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.proto.ImgClassify.ImgClassify.imgs.img.class, com.proto.ImgClassify.ImgClassify.imgs.img.Builder.class);
        }

        // Construct using com.proto.ImgClassify.ImgClassify.imgs.img.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          singleImg_ = emptyIntList();
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.proto.ImgClassify.ImgClassify.internal_static_gesture_rpc_imgs_img_descriptor;
        }

        @java.lang.Override
        public com.proto.ImgClassify.ImgClassify.imgs.img getDefaultInstanceForType() {
          return com.proto.ImgClassify.ImgClassify.imgs.img.getDefaultInstance();
        }

        @java.lang.Override
        public com.proto.ImgClassify.ImgClassify.imgs.img build() {
          com.proto.ImgClassify.ImgClassify.imgs.img result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.proto.ImgClassify.ImgClassify.imgs.img buildPartial() {
          com.proto.ImgClassify.ImgClassify.imgs.img result = new com.proto.ImgClassify.ImgClassify.imgs.img(this);
          int from_bitField0_ = bitField0_;
          if (((bitField0_ & 0x00000001) != 0)) {
            singleImg_.makeImmutable();
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.singleImg_ = singleImg_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.proto.ImgClassify.ImgClassify.imgs.img) {
            return mergeFrom((com.proto.ImgClassify.ImgClassify.imgs.img)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.proto.ImgClassify.ImgClassify.imgs.img other) {
          if (other == com.proto.ImgClassify.ImgClassify.imgs.img.getDefaultInstance()) return this;
          if (!other.singleImg_.isEmpty()) {
            if (singleImg_.isEmpty()) {
              singleImg_ = other.singleImg_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSingleImgIsMutable();
              singleImg_.addAll(other.singleImg_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.proto.ImgClassify.ImgClassify.imgs.img parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.proto.ImgClassify.ImgClassify.imgs.img) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private com.google.protobuf.Internal.IntList singleImg_ = emptyIntList();
        private void ensureSingleImgIsMutable() {
          if (!((bitField0_ & 0x00000001) != 0)) {
            singleImg_ = mutableCopy(singleImg_);
            bitField0_ |= 0x00000001;
           }
        }
        /**
         * <code>repeated int32 single_img = 1;</code>
         */
        public java.util.List<java.lang.Integer>
            getSingleImgList() {
          return ((bitField0_ & 0x00000001) != 0) ?
                   java.util.Collections.unmodifiableList(singleImg_) : singleImg_;
        }
        /**
         * <code>repeated int32 single_img = 1;</code>
         */
        public int getSingleImgCount() {
          return singleImg_.size();
        }
        /**
         * <code>repeated int32 single_img = 1;</code>
         */
        public int getSingleImg(int index) {
          return singleImg_.getInt(index);
        }
        /**
         * <code>repeated int32 single_img = 1;</code>
         */
        public Builder setSingleImg(
            int index, int value) {
          ensureSingleImgIsMutable();
          singleImg_.setInt(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 single_img = 1;</code>
         */
        public Builder addSingleImg(int value) {
          ensureSingleImgIsMutable();
          singleImg_.addInt(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 single_img = 1;</code>
         */
        public Builder addAllSingleImg(
            java.lang.Iterable<? extends java.lang.Integer> values) {
          ensureSingleImgIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, singleImg_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 single_img = 1;</code>
         */
        public Builder clearSingleImg() {
          singleImg_ = emptyIntList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:gesture_rpc.imgs.img)
      }

      // @@protoc_insertion_point(class_scope:gesture_rpc.imgs.img)
      private static final com.proto.ImgClassify.ImgClassify.imgs.img DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.proto.ImgClassify.ImgClassify.imgs.img();
      }

      public static com.proto.ImgClassify.ImgClassify.imgs.img getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<img>
          PARSER = new com.google.protobuf.AbstractParser<img>() {
        @java.lang.Override
        public img parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new img(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<img> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<img> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.proto.ImgClassify.ImgClassify.imgs.img getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object iD_;
    /**
     * <code>string ID = 1;</code>
     */
    public java.lang.String getID() {
      java.lang.Object ref = iD_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iD_ = s;
        return s;
      }
    }
    /**
     * <code>string ID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIDBytes() {
      java.lang.Object ref = iD_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iD_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUM_IMG_FIELD_NUMBER = 2;
    private int numImg_;
    /**
     * <code>int32 num_img = 2;</code>
     */
    public int getNumImg() {
      return numImg_;
    }

    public static final int ALL_IMG_FIELD_NUMBER = 3;
    private java.util.List<com.proto.ImgClassify.ImgClassify.imgs.img> allImg_;
    /**
     * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
     */
    public java.util.List<com.proto.ImgClassify.ImgClassify.imgs.img> getAllImgList() {
      return allImg_;
    }
    /**
     * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
     */
    public java.util.List<? extends com.proto.ImgClassify.ImgClassify.imgs.imgOrBuilder> 
        getAllImgOrBuilderList() {
      return allImg_;
    }
    /**
     * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
     */
    public int getAllImgCount() {
      return allImg_.size();
    }
    /**
     * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
     */
    public com.proto.ImgClassify.ImgClassify.imgs.img getAllImg(int index) {
      return allImg_.get(index);
    }
    /**
     * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
     */
    public com.proto.ImgClassify.ImgClassify.imgs.imgOrBuilder getAllImgOrBuilder(
        int index) {
      return allImg_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, iD_);
      }
      if (numImg_ != 0) {
        output.writeInt32(2, numImg_);
      }
      for (int i = 0; i < allImg_.size(); i++) {
        output.writeMessage(3, allImg_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, iD_);
      }
      if (numImg_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, numImg_);
      }
      for (int i = 0; i < allImg_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, allImg_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.proto.ImgClassify.ImgClassify.imgs)) {
        return super.equals(obj);
      }
      com.proto.ImgClassify.ImgClassify.imgs other = (com.proto.ImgClassify.ImgClassify.imgs) obj;

      if (!getID()
          .equals(other.getID())) return false;
      if (getNumImg()
          != other.getNumImg()) return false;
      if (!getAllImgList()
          .equals(other.getAllImgList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getID().hashCode();
      hash = (37 * hash) + NUM_IMG_FIELD_NUMBER;
      hash = (53 * hash) + getNumImg();
      if (getAllImgCount() > 0) {
        hash = (37 * hash) + ALL_IMG_FIELD_NUMBER;
        hash = (53 * hash) + getAllImgList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.proto.ImgClassify.ImgClassify.imgs parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.ImgClassify.ImgClassify.imgs parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.ImgClassify.ImgClassify.imgs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.ImgClassify.ImgClassify.imgs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.ImgClassify.ImgClassify.imgs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.ImgClassify.ImgClassify.imgs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.ImgClassify.ImgClassify.imgs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.ImgClassify.ImgClassify.imgs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.ImgClassify.ImgClassify.imgs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.proto.ImgClassify.ImgClassify.imgs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.ImgClassify.ImgClassify.imgs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.ImgClassify.ImgClassify.imgs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.proto.ImgClassify.ImgClassify.imgs prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gesture_rpc.imgs}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gesture_rpc.imgs)
        com.proto.ImgClassify.ImgClassify.imgsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.proto.ImgClassify.ImgClassify.internal_static_gesture_rpc_imgs_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.proto.ImgClassify.ImgClassify.internal_static_gesture_rpc_imgs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.proto.ImgClassify.ImgClassify.imgs.class, com.proto.ImgClassify.ImgClassify.imgs.Builder.class);
      }

      // Construct using com.proto.ImgClassify.ImgClassify.imgs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAllImgFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        iD_ = "";

        numImg_ = 0;

        if (allImgBuilder_ == null) {
          allImg_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          allImgBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.proto.ImgClassify.ImgClassify.internal_static_gesture_rpc_imgs_descriptor;
      }

      @java.lang.Override
      public com.proto.ImgClassify.ImgClassify.imgs getDefaultInstanceForType() {
        return com.proto.ImgClassify.ImgClassify.imgs.getDefaultInstance();
      }

      @java.lang.Override
      public com.proto.ImgClassify.ImgClassify.imgs build() {
        com.proto.ImgClassify.ImgClassify.imgs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.proto.ImgClassify.ImgClassify.imgs buildPartial() {
        com.proto.ImgClassify.ImgClassify.imgs result = new com.proto.ImgClassify.ImgClassify.imgs(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.iD_ = iD_;
        result.numImg_ = numImg_;
        if (allImgBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            allImg_ = java.util.Collections.unmodifiableList(allImg_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.allImg_ = allImg_;
        } else {
          result.allImg_ = allImgBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.proto.ImgClassify.ImgClassify.imgs) {
          return mergeFrom((com.proto.ImgClassify.ImgClassify.imgs)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.proto.ImgClassify.ImgClassify.imgs other) {
        if (other == com.proto.ImgClassify.ImgClassify.imgs.getDefaultInstance()) return this;
        if (!other.getID().isEmpty()) {
          iD_ = other.iD_;
          onChanged();
        }
        if (other.getNumImg() != 0) {
          setNumImg(other.getNumImg());
        }
        if (allImgBuilder_ == null) {
          if (!other.allImg_.isEmpty()) {
            if (allImg_.isEmpty()) {
              allImg_ = other.allImg_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureAllImgIsMutable();
              allImg_.addAll(other.allImg_);
            }
            onChanged();
          }
        } else {
          if (!other.allImg_.isEmpty()) {
            if (allImgBuilder_.isEmpty()) {
              allImgBuilder_.dispose();
              allImgBuilder_ = null;
              allImg_ = other.allImg_;
              bitField0_ = (bitField0_ & ~0x00000004);
              allImgBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAllImgFieldBuilder() : null;
            } else {
              allImgBuilder_.addAllMessages(other.allImg_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.proto.ImgClassify.ImgClassify.imgs parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.proto.ImgClassify.ImgClassify.imgs) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object iD_ = "";
      /**
       * <code>string ID = 1;</code>
       */
      public java.lang.String getID() {
        java.lang.Object ref = iD_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          iD_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIDBytes() {
        java.lang.Object ref = iD_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iD_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ID = 1;</code>
       */
      public Builder setID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        iD_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ID = 1;</code>
       */
      public Builder clearID() {
        
        iD_ = getDefaultInstance().getID();
        onChanged();
        return this;
      }
      /**
       * <code>string ID = 1;</code>
       */
      public Builder setIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        iD_ = value;
        onChanged();
        return this;
      }

      private int numImg_ ;
      /**
       * <code>int32 num_img = 2;</code>
       */
      public int getNumImg() {
        return numImg_;
      }
      /**
       * <code>int32 num_img = 2;</code>
       */
      public Builder setNumImg(int value) {
        
        numImg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 num_img = 2;</code>
       */
      public Builder clearNumImg() {
        
        numImg_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.proto.ImgClassify.ImgClassify.imgs.img> allImg_ =
        java.util.Collections.emptyList();
      private void ensureAllImgIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          allImg_ = new java.util.ArrayList<com.proto.ImgClassify.ImgClassify.imgs.img>(allImg_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.proto.ImgClassify.ImgClassify.imgs.img, com.proto.ImgClassify.ImgClassify.imgs.img.Builder, com.proto.ImgClassify.ImgClassify.imgs.imgOrBuilder> allImgBuilder_;

      /**
       * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
       */
      public java.util.List<com.proto.ImgClassify.ImgClassify.imgs.img> getAllImgList() {
        if (allImgBuilder_ == null) {
          return java.util.Collections.unmodifiableList(allImg_);
        } else {
          return allImgBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
       */
      public int getAllImgCount() {
        if (allImgBuilder_ == null) {
          return allImg_.size();
        } else {
          return allImgBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
       */
      public com.proto.ImgClassify.ImgClassify.imgs.img getAllImg(int index) {
        if (allImgBuilder_ == null) {
          return allImg_.get(index);
        } else {
          return allImgBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
       */
      public Builder setAllImg(
          int index, com.proto.ImgClassify.ImgClassify.imgs.img value) {
        if (allImgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllImgIsMutable();
          allImg_.set(index, value);
          onChanged();
        } else {
          allImgBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
       */
      public Builder setAllImg(
          int index, com.proto.ImgClassify.ImgClassify.imgs.img.Builder builderForValue) {
        if (allImgBuilder_ == null) {
          ensureAllImgIsMutable();
          allImg_.set(index, builderForValue.build());
          onChanged();
        } else {
          allImgBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
       */
      public Builder addAllImg(com.proto.ImgClassify.ImgClassify.imgs.img value) {
        if (allImgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllImgIsMutable();
          allImg_.add(value);
          onChanged();
        } else {
          allImgBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
       */
      public Builder addAllImg(
          int index, com.proto.ImgClassify.ImgClassify.imgs.img value) {
        if (allImgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllImgIsMutable();
          allImg_.add(index, value);
          onChanged();
        } else {
          allImgBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
       */
      public Builder addAllImg(
          com.proto.ImgClassify.ImgClassify.imgs.img.Builder builderForValue) {
        if (allImgBuilder_ == null) {
          ensureAllImgIsMutable();
          allImg_.add(builderForValue.build());
          onChanged();
        } else {
          allImgBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
       */
      public Builder addAllImg(
          int index, com.proto.ImgClassify.ImgClassify.imgs.img.Builder builderForValue) {
        if (allImgBuilder_ == null) {
          ensureAllImgIsMutable();
          allImg_.add(index, builderForValue.build());
          onChanged();
        } else {
          allImgBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
       */
      public Builder addAllAllImg(
          java.lang.Iterable<? extends com.proto.ImgClassify.ImgClassify.imgs.img> values) {
        if (allImgBuilder_ == null) {
          ensureAllImgIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, allImg_);
          onChanged();
        } else {
          allImgBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
       */
      public Builder clearAllImg() {
        if (allImgBuilder_ == null) {
          allImg_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          allImgBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
       */
      public Builder removeAllImg(int index) {
        if (allImgBuilder_ == null) {
          ensureAllImgIsMutable();
          allImg_.remove(index);
          onChanged();
        } else {
          allImgBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
       */
      public com.proto.ImgClassify.ImgClassify.imgs.img.Builder getAllImgBuilder(
          int index) {
        return getAllImgFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
       */
      public com.proto.ImgClassify.ImgClassify.imgs.imgOrBuilder getAllImgOrBuilder(
          int index) {
        if (allImgBuilder_ == null) {
          return allImg_.get(index);  } else {
          return allImgBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
       */
      public java.util.List<? extends com.proto.ImgClassify.ImgClassify.imgs.imgOrBuilder> 
           getAllImgOrBuilderList() {
        if (allImgBuilder_ != null) {
          return allImgBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(allImg_);
        }
      }
      /**
       * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
       */
      public com.proto.ImgClassify.ImgClassify.imgs.img.Builder addAllImgBuilder() {
        return getAllImgFieldBuilder().addBuilder(
            com.proto.ImgClassify.ImgClassify.imgs.img.getDefaultInstance());
      }
      /**
       * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
       */
      public com.proto.ImgClassify.ImgClassify.imgs.img.Builder addAllImgBuilder(
          int index) {
        return getAllImgFieldBuilder().addBuilder(
            index, com.proto.ImgClassify.ImgClassify.imgs.img.getDefaultInstance());
      }
      /**
       * <code>repeated .gesture_rpc.imgs.img all_img = 3;</code>
       */
      public java.util.List<com.proto.ImgClassify.ImgClassify.imgs.img.Builder> 
           getAllImgBuilderList() {
        return getAllImgFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.proto.ImgClassify.ImgClassify.imgs.img, com.proto.ImgClassify.ImgClassify.imgs.img.Builder, com.proto.ImgClassify.ImgClassify.imgs.imgOrBuilder> 
          getAllImgFieldBuilder() {
        if (allImgBuilder_ == null) {
          allImgBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.proto.ImgClassify.ImgClassify.imgs.img, com.proto.ImgClassify.ImgClassify.imgs.img.Builder, com.proto.ImgClassify.ImgClassify.imgs.imgOrBuilder>(
                  allImg_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          allImg_ = null;
        }
        return allImgBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gesture_rpc.imgs)
    }

    // @@protoc_insertion_point(class_scope:gesture_rpc.imgs)
    private static final com.proto.ImgClassify.ImgClassify.imgs DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.proto.ImgClassify.ImgClassify.imgs();
    }

    public static com.proto.ImgClassify.ImgClassify.imgs getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<imgs>
        PARSER = new com.google.protobuf.AbstractParser<imgs>() {
      @java.lang.Override
      public imgs parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new imgs(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<imgs> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<imgs> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.proto.ImgClassify.ImgClassify.imgs getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface classifiedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gesture_rpc.classified)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 num_img = 1;</code>
     */
    int getNumImg();

    /**
     * <code>repeated string classes = 2;</code>
     */
    java.util.List<java.lang.String>
        getClassesList();
    /**
     * <code>repeated string classes = 2;</code>
     */
    int getClassesCount();
    /**
     * <code>repeated string classes = 2;</code>
     */
    java.lang.String getClasses(int index);
    /**
     * <code>repeated string classes = 2;</code>
     */
    com.google.protobuf.ByteString
        getClassesBytes(int index);
  }
  /**
   * Protobuf type {@code gesture_rpc.classified}
   */
  public  static final class classified extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gesture_rpc.classified)
      classifiedOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use classified.newBuilder() to construct.
    private classified(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private classified() {
      classes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private classified(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              numImg_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                classes_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              classes_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          classes_ = classes_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.ImgClassify.ImgClassify.internal_static_gesture_rpc_classified_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.ImgClassify.ImgClassify.internal_static_gesture_rpc_classified_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.ImgClassify.ImgClassify.classified.class, com.proto.ImgClassify.ImgClassify.classified.Builder.class);
    }

    private int bitField0_;
    public static final int NUM_IMG_FIELD_NUMBER = 1;
    private int numImg_;
    /**
     * <code>int32 num_img = 1;</code>
     */
    public int getNumImg() {
      return numImg_;
    }

    public static final int CLASSES_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList classes_;
    /**
     * <code>repeated string classes = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getClassesList() {
      return classes_;
    }
    /**
     * <code>repeated string classes = 2;</code>
     */
    public int getClassesCount() {
      return classes_.size();
    }
    /**
     * <code>repeated string classes = 2;</code>
     */
    public java.lang.String getClasses(int index) {
      return classes_.get(index);
    }
    /**
     * <code>repeated string classes = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClassesBytes(int index) {
      return classes_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (numImg_ != 0) {
        output.writeInt32(1, numImg_);
      }
      for (int i = 0; i < classes_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, classes_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (numImg_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, numImg_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < classes_.size(); i++) {
          dataSize += computeStringSizeNoTag(classes_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getClassesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.proto.ImgClassify.ImgClassify.classified)) {
        return super.equals(obj);
      }
      com.proto.ImgClassify.ImgClassify.classified other = (com.proto.ImgClassify.ImgClassify.classified) obj;

      if (getNumImg()
          != other.getNumImg()) return false;
      if (!getClassesList()
          .equals(other.getClassesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUM_IMG_FIELD_NUMBER;
      hash = (53 * hash) + getNumImg();
      if (getClassesCount() > 0) {
        hash = (37 * hash) + CLASSES_FIELD_NUMBER;
        hash = (53 * hash) + getClassesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.proto.ImgClassify.ImgClassify.classified parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.ImgClassify.ImgClassify.classified parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.ImgClassify.ImgClassify.classified parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.ImgClassify.ImgClassify.classified parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.ImgClassify.ImgClassify.classified parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.ImgClassify.ImgClassify.classified parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.ImgClassify.ImgClassify.classified parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.ImgClassify.ImgClassify.classified parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.ImgClassify.ImgClassify.classified parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.proto.ImgClassify.ImgClassify.classified parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.ImgClassify.ImgClassify.classified parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.ImgClassify.ImgClassify.classified parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.proto.ImgClassify.ImgClassify.classified prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gesture_rpc.classified}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gesture_rpc.classified)
        com.proto.ImgClassify.ImgClassify.classifiedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.proto.ImgClassify.ImgClassify.internal_static_gesture_rpc_classified_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.proto.ImgClassify.ImgClassify.internal_static_gesture_rpc_classified_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.proto.ImgClassify.ImgClassify.classified.class, com.proto.ImgClassify.ImgClassify.classified.Builder.class);
      }

      // Construct using com.proto.ImgClassify.ImgClassify.classified.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        numImg_ = 0;

        classes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.proto.ImgClassify.ImgClassify.internal_static_gesture_rpc_classified_descriptor;
      }

      @java.lang.Override
      public com.proto.ImgClassify.ImgClassify.classified getDefaultInstanceForType() {
        return com.proto.ImgClassify.ImgClassify.classified.getDefaultInstance();
      }

      @java.lang.Override
      public com.proto.ImgClassify.ImgClassify.classified build() {
        com.proto.ImgClassify.ImgClassify.classified result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.proto.ImgClassify.ImgClassify.classified buildPartial() {
        com.proto.ImgClassify.ImgClassify.classified result = new com.proto.ImgClassify.ImgClassify.classified(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.numImg_ = numImg_;
        if (((bitField0_ & 0x00000002) != 0)) {
          classes_ = classes_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.classes_ = classes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.proto.ImgClassify.ImgClassify.classified) {
          return mergeFrom((com.proto.ImgClassify.ImgClassify.classified)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.proto.ImgClassify.ImgClassify.classified other) {
        if (other == com.proto.ImgClassify.ImgClassify.classified.getDefaultInstance()) return this;
        if (other.getNumImg() != 0) {
          setNumImg(other.getNumImg());
        }
        if (!other.classes_.isEmpty()) {
          if (classes_.isEmpty()) {
            classes_ = other.classes_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureClassesIsMutable();
            classes_.addAll(other.classes_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.proto.ImgClassify.ImgClassify.classified parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.proto.ImgClassify.ImgClassify.classified) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int numImg_ ;
      /**
       * <code>int32 num_img = 1;</code>
       */
      public int getNumImg() {
        return numImg_;
      }
      /**
       * <code>int32 num_img = 1;</code>
       */
      public Builder setNumImg(int value) {
        
        numImg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 num_img = 1;</code>
       */
      public Builder clearNumImg() {
        
        numImg_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList classes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureClassesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          classes_ = new com.google.protobuf.LazyStringArrayList(classes_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string classes = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getClassesList() {
        return classes_.getUnmodifiableView();
      }
      /**
       * <code>repeated string classes = 2;</code>
       */
      public int getClassesCount() {
        return classes_.size();
      }
      /**
       * <code>repeated string classes = 2;</code>
       */
      public java.lang.String getClasses(int index) {
        return classes_.get(index);
      }
      /**
       * <code>repeated string classes = 2;</code>
       */
      public com.google.protobuf.ByteString
          getClassesBytes(int index) {
        return classes_.getByteString(index);
      }
      /**
       * <code>repeated string classes = 2;</code>
       */
      public Builder setClasses(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClassesIsMutable();
        classes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string classes = 2;</code>
       */
      public Builder addClasses(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClassesIsMutable();
        classes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string classes = 2;</code>
       */
      public Builder addAllClasses(
          java.lang.Iterable<java.lang.String> values) {
        ensureClassesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, classes_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string classes = 2;</code>
       */
      public Builder clearClasses() {
        classes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string classes = 2;</code>
       */
      public Builder addClassesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureClassesIsMutable();
        classes_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gesture_rpc.classified)
    }

    // @@protoc_insertion_point(class_scope:gesture_rpc.classified)
    private static final com.proto.ImgClassify.ImgClassify.classified DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.proto.ImgClassify.ImgClassify.classified();
    }

    public static com.proto.ImgClassify.ImgClassify.classified getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<classified>
        PARSER = new com.google.protobuf.AbstractParser<classified>() {
      @java.lang.Override
      public classified parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new classified(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<classified> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<classified> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.proto.ImgClassify.ImgClassify.classified getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gesture_rpc_imgs_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gesture_rpc_imgs_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gesture_rpc_imgs_img_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gesture_rpc_imgs_img_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gesture_rpc_classified_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gesture_rpc_classified_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ImgClassify.proto\022\013gesture_rpc\"f\n\004imgs" +
      "\022\n\n\002ID\030\001 \001(\t\022\017\n\007num_img\030\002 \001(\005\022&\n\007all_img" +
      "\030\003 \003(\0132\025.gesture_rpc.imgs.img\032\031\n\003img\022\022\n\n" +
      "single_img\030\001 \003(\005\".\n\nclassified\022\017\n\007num_im" +
      "g\030\001 \001(\005\022\017\n\007classes\030\002 \003(\t2U\n\017ClassifyServ" +
      "ice\022B\n\016ClassifyImages\022\021.gesture_rpc.imgs" +
      "\032\027.gesture_rpc.classified\"\000(\0010\001B\027\n\025com.p" +
      "roto.ImgClassifyb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_gesture_rpc_imgs_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gesture_rpc_imgs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gesture_rpc_imgs_descriptor,
        new java.lang.String[] { "ID", "NumImg", "AllImg", });
    internal_static_gesture_rpc_imgs_img_descriptor =
      internal_static_gesture_rpc_imgs_descriptor.getNestedTypes().get(0);
    internal_static_gesture_rpc_imgs_img_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gesture_rpc_imgs_img_descriptor,
        new java.lang.String[] { "SingleImg", });
    internal_static_gesture_rpc_classified_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gesture_rpc_classified_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gesture_rpc_classified_descriptor,
        new java.lang.String[] { "NumImg", "Classes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
